[package]
name = "tcm"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Rust port of TCM (tcbot macro) format for Geometry Dash"
repository = "https://github.com/tcbot-gd/tcm-rs"
keywords = ["gd", "geode", "bot"]

[dependencies]
thiserror = "2.0.16"
